### ISSUE TITLE
Using this module will disables SSG for all pages?!

### ISSUE THREAD

**Issue by hk86** [moxystudio/next-intl#14]
Hello,

I'm using Next.js 9.4 and would like to use SSG. Will this module disable it for all my pages?

Best regards,

HK

**Comment by satazor** [comment]
@hk86 yes it will disable by default, but you may opt-in for SSG again by adding getStaticProps in your pages.

Down the road we will improve SSG support when Next.js adds the ability to specify getStaticProps in _app.js.
