### ISSUE TITLE
__NEXT_INTL_POLYFILL_URL__ is not defined

### ISSUE THREAD

**Issue by neomad1337** [moxystudio/next-intl#15]
Hello, i did everything according to the guide. In development mode I got this error 
`> Ready on http://127.0.0.1:3000
[ event ] build page: /404
[ wait ]  compiling ...
[ event ] build page: /
[ error ] ReferenceError: __NEXT_INTL_POLYFILL_URL__ is not defined`

Everything worked after disabling "use strict" in tsconfig. I'm not sure if this is the best way.

**Comment by WaysToGo** [comment]
same here 
Error: Could not locale the polyfill URL, did you forgot to enable the plugin in the next.config.js file?
    at NextIntlScript (node_modules/.pnpm/registry.npmjs.org/@moxy/next-
intl/2.1.1_a456420d4da5b276256d138d0d31e927/node_modules/@moxy/next-intl/lib/react/NextIntlScript.js:31:11)

**Comment by satazor** [comment]
Hmmm, that’s strange. Perhaps in strict mode globals can’t be accessed in TS? I’m not very familiar with it, but I can help if you put together a repository to reproduce the error.

**Comment by satazor** [comment]
Closing as there was no further response. I will reopen if necessary.
