### ISSUE TITLE
Content Security Policy issue with injected <script />

### ISSUE THREAD

**Issue by DenisBiondic** [moxystudio/next-intl#18]
This code here is a cause of CSP violation: https://content-security-policy.com/unsafe-inline/

https://github.com/moxystudio/next-intl/blob/edd7f782208f8a85de7a1b37594bb896b85bde71/src/react/NextIntlScript.js#L26

Do you have any recommendation around this issue (except disabling the CSP rule)?

**Comment by satazor** [comment]
Hello!

The generated URL should be on the same origin, so it should not violate CSP. Can you console.log the script URL to confirm that it has the same origin?

**Comment by satazor** [comment]
Oh I see. It’s because of the fact that we inject an inline script. To circumvent this issue we could instead emit a asset in the webpack plugin, which includes the script. Then we would simply inject a script tag pointing to the asset link.

It should not be hard to do this. Are you willing to do a PR?

**Comment by satazor** [comment]
There’s one downside however. For evergreen browsers that don’t require the polyfills, will have to download this asset.

**Comment by satazor** [comment]
@DenisBiondic what I was suggesting was to move the inline JS to a chunk that lives in a URL. However, this JS chink would decide to load the polyfill or not, meaning all browsers would need to download this small chunk.

Another strategy would be to use a nounce or hashes to allow specific inline scripts. I think we can’t use hashes as they are based on the contents of script, and the content of the script will change as the polyfill URL also changes. So a nounce seems to be better.

https://content-security-policy.com/nonce/

If that works, we just need to support a nounce prop in the NextIntlScript component and that’s it.

**Comment by satazor** [comment]
My first suggestion works out of the box and it’s not really gonna hurt performance when using HTTP 2.

**Comment by satazor** [comment]
@moxy/next-intl v3 was released, which embraces the new Next.js i18n capabilities.

We no longer inject script tags, so I'm going to close this issue.
