### ISSUE TITLE
Module not found: Can't resolve '@formatjs/intl-displaynames/polyfill-locales'

### ISSUE THREAD

**Issue by nigampatel** [moxystudio/next-intl#20]
I just tried to use this plugin in my app, which is a very basic app.

I get the following error when I try to do `npm run dev`

```
error - ./node_modules/@moxy/next-intl/es/polyfill.browser.js:15:0
Module not found: Can't resolve '@formatjs/intl-displaynames/polyfill-locales'
```
I followed all the steps required not sure why I'm getting the error.

**Comment by shicholas** [comment]
I ran into this too, it should work if `react-intl` is `^5.13.5`.

**Comment by satazor** [comment]
`@moxy/next-intl` v3 was released, which embraces the new Next.js i18n capabilities.

In this new version, we no longer load polyfills automatically, but there's a section in the README explaining how to.
