### ISSUE TITLE
intl object

### ISSUE THREAD

**Issue by morsaken** [moxystudio/next-intl#22]
I was getting intl object in previous version. The question is how should i get "intl" object?

**Comment by satazor** [comment]
@morsaken what do you need from the intl object? If it’s the locale, locales or defaultLocale they are available in Next.js router

**Comment by morsaken** [comment]
hi again, i use intl.formatMessage method in some cases. I have to reach react-intl methods.

**Comment by satazor** [comment]
You may use the `useIntl` hook from react-intl:

```js
import { useIntl } from 'react-intl'
```

https://formatjs.io/docs/react-intl/api
